# Generated by Django 5.0.6 on 2024-06-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
